import socket

# MSG CONFIG
HEADER = 64
FORMAT = "utf-8"

# SOCKET CONN
SERVER = socket.gethostbyname(socket.gethostname())
USERNAME = "TEST"
PORT = 5001
ADDR = (SERVER, PORT)

# SYSTEM MSGM
DISCONNECT_MESSAGE = "[DISCONNECT]"
OP = 0
NEW_MESSAGE = 0
DEFINE_NAME = 1
PROBLEM_NAME = 2
NAME_LIST = '3'
NAME_LIST_END = 'l'

